# Windows

map cmd+h neighboring_window left
map cmd+j neighboring_window down
map cmd+k neighboring_window up
map cmd+l neighboring_window right

map shift+cmd+h move_window left
map shift+cmd+j move_window down
map shift+cmd+l move_window right
map shift+cmd+k move_window up

map ctrl+cmd+= resize_window reset

# Tabs

map ctrl+cmd+h previous_tab
map ctrl+cmd+l next_tab

map ctrl+cmd+k move_tab_forward
map ctrl+cmd+j move_tab_backward

# Sessions

map shift+cmd+s goto_session ~/.config/kitty/sessions

# Layouts

map cmd+s next_layout

map cmd+b layout_action bias 40 60
map cmd+m layout_action mirror toggle

map cmd+[ layout_action decrease_num_full_size_windows
map cmd+] layout_action increase_num_full_size_windows

map cmd+g detach_window ask
map cmd+r set_tab_title

map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9
map cmd+0 goto_tab 0

map cmd+enter launch --cwd=current
