# Text
font_family      family="MesloLGS Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        15
text_composition_strategy legacy
disable_ligatures cursor

inactive_text_alpha 0.2

term xterm-256color
scrollback_lines 5000

remember_window_size no
nitial_window_width  1500
initial_window_height 1000
remember_window_size no
hide_window_decorations titlebar-and-corners
confirm_os_window_close 0

window_border_width     1pt
window_margin_width     2
single_window_margin_width 0

enabled_layouts grid,horizontal,vertical,tall:bias=75,fat:bias=75

startup_session ~/.config/kitty/sessions/maximized.conf
macos_quit_when_last_window_closed yes

tab_bar_style fade
tab_bar_align center
tab_title_max_length 50

active_tab_foreground #000
active_tab_background #999
inactive_tab_foreground #999
inactive_tab_background #333
active_border_color #999
inactive_border_color #333
#background #111

# Cursor Configuration
cursor_shape block
cursor_trail 1
cursor_trail_decay 0.1 0.30
cursor_trail_start_threshold 2

# Clipboard/Paste Configuration
clipboard_control write-clipboard write-primary read-clipboard read-primary no-append
select_by_word_characters @-./_~?&=%+#
strip_trailing_spaces
copy_on_select clipboard
paste_actions quote-urls-at-prompt

# MacOS Specific
macos_option_as_alt yes
macos_show_window_title_in none

# Mouse Configuration
mouse_map ctrl+left press ungrabbed,grabbed mouse_click_url
open_url_with default

mouse_hide_wait	-3.0

include keybindings.conf
