theme = "ayu_dark"

[editor]
line-number = "relative"
mouse = true
auto-completion = true
auto-format = true
color-modes = true
cursorline = true
bufferline = "always"
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
scrolloff = 10
path-completion = true
preview-completion-insert = false
popup-border = "all"
jump-label-alphabet = "fjdkslaghrueiwoqptyvncmbxz"
end-of-line-diagnostics = "hint"

[editor.indent-guides]
render = true
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

#[editor.file-picker]
#hidden = false

[editor.statusline]
left = ["mode", "separator", "version-control"]
center = ["file-name", "read-only-indicator", "file-modification-indicator"]
right = [
  "diagnostics",
  "workspace-diagnostics",
  "position",
  "total-line-numbers",
  "position-percentage",
  "file-encoding",
  "file-line-ending",
  "file-type",
  "register",
  "selections",
  "spinner",
]
separator = " "
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.whitespace.render]
space = "all"
tab = "all"

[editor.lsp]
enable = true
auto-signature-help = true
display-messages = true
display-inlay-hints = true
display-signature-help-docs = true
snippets = true
goto-reference-include-declaration = true

[keys.normal]
C-u = ["half_page_up", "align_view_center"]
C-d = ["half_page_down", "align_view_center"]
C-r = [":reload"]

[keys.normal.space.o]
g = [":write-all", ":insert-output lazygit >/dev/tty", ":redraw", ":reload-all"]
y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
