[[language]]
name = "hcl"
language-servers = [ "terraform-ls" ]
language-id = "terraform"
formatter = { command = "terraform" , args = ["fmt", "-"] }

[[language]]
name = "tfvars"
language-servers = [ "terraform-ls" ]
language-id = "terraform-vars"

[language-server.terraform-ls]
command = "terraform-ls"
args = ["serve"]

[[language]]
name = "rust"
auto-format = true

roots = [
  "Cargo.toml",
  "Cargo.lock"
]

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
check.command = "clippy"
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false

[[language]]
name = "toml"
formatter = { command = "prettier" }
auto-format = true

[[language]]
name = "yaml"
formatter = { command = "prettier" }
auto-format = true

[[language]]
name = "dockerfile"
file-types = ["Dockerfile", "Dockerfile.lambda"]
auto-format = true

