[directory]
truncation_symbol = "…/"

[git_branch]
always_show_remote = true

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
staged = '[++\($count\)](green)'
