command_timeout = 5000

[git_branch]
always_show_remote = true

[git_metrics]
disabled = true
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[directory]
truncation_length = 3
truncation_symbol = ".../"
truncate_to_repo = true
